databaseChangeLog:
  - changeSet:
      id: 202407281800_insert_default_movie_values
      author: arabkhan
      changes:
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: name
                  value: "Inception"
              - column:
                  name: description
                  value: "A mind-bending thriller where dream invasion is possible."
              - column:
                  name: genre
                  value: "Sci-Fi"
              - column:
                  name: release_date
                  value: "2010-07-16"
              - column:
                  name: age_restriction
                  value: 13
              - column:
                  name: duration
                  value: "148"
              - column:
                  name: background_image
                  value: "/images/inception_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/inception_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "2010-07-16"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 2
              - column:
                  name: name
                  value: "The Matrix"
              - column:
                  name: description
                  value: "A computer hacker learns about the true nature of his reality."
              - column:
                  name: genre
                  value: "Action"
              - column:
                  name: release_date
                  value: "1999-03-31"
              - column:
                  name: age_restriction
                  value: 16
              - column:
                  name: duration
                  value: "136"
              - column:
                  name: background_image
                  value: "/images/matrix_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/matrix_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "1999-03-31"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 3
              - column:
                  name: name
                  value: "Interstellar"
              - column:
                  name: description
                  value: "A team of explorers travel through a wormhole in space."
              - column:
                  name: genre
                  value: "Sci-Fi"
              - column:
                  name: release_date
                  value: "2014-11-07"
              - column:
                  name: age_restriction
                  value: 13
              - column:
                  name: duration
                  value: "169"
              - column:
                  name: background_image
                  value: "/images/interstellar_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/interstellar_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "2014-11-07"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 4
              - column:
                  name: name
                  value: "The Dark Knight"
              - column:
                  name: description
                  value: "Batman faces the Joker in this superhero film."
              - column:
                  name: genre
                  value: "Action"
              - column:
                  name: release_date
                  value: "2008-07-18"
              - column:
                  name: age_restriction
                  value: 13
              - column:
                  name: duration
                  value: "152"
              - column:
                  name: background_image
                  value: "/images/dark_knight_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/dark_knight_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "2008-07-18"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 5
              - column:
                  name: name
                  value: "Pulp Fiction"
              - column:
                  name: description
                  value: "The lives of two mob hitmen, a boxer, and others intertwine."
              - column:
                  name: genre
                  value: "Crime"
              - column:
                  name: release_date
                  value: "1994-10-14"
              - column:
                  name: age_restriction
                  value: 18
              - column:
                  name: duration
                  value: "154"
              - column:
                  name: background_image
                  value: "/images/pulp_fiction_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/pulp_fiction_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "1994-10-14"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 6
              - column:
                  name: name
                  value: "Forrest Gump"
              - column:
                  name: description
                  value: "The life story of an intellectually disabled man."
              - column:
                  name: genre
                  value: "Drama"
              - column:
                  name: release_date
                  value: "1994-07-06"
              - column:
                  name: age_restriction
                  value: 13
              - column:
                  name: duration
                  value: "142"
              - column:
                  name: background_image
                  value: "/images/forrest_gump_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/forrest_gump_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "1994-07-06"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 7
              - column:
                  name: name
                  value: "The Shawshank Redemption"
              - column:
                  name: description
                  value: "Two imprisoned men bond over years, finding solace and redemption."
              - column:
                  name: genre
                  value: "Drama"
              - column:
                  name: release_date
                  value: "1994-09-23"
              - column:
                  name: age_restriction
                  value: 16
              - column:
                  name: duration
                  value: "142"
              - column:
                  name: background_image
                  value: "/images/shawshank_redemption_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/shawshank_redemption_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "1994-09-23"
        - insert:
            tableName: movies
            columns:
              - column:
                  name: id
                  value: 8
              - column:
                  name: name
                  value: "Fight Club"
              - column:
                  name: description
                  value: "An insomniac and a soap salesman form an underground fight club."
              - column:
                  name: genre
                  value: "Drama"
              - column:
                  name: release_date
                  value: "1999-10-15"
              - column:
                  name: age_restriction
                  value: 18
              - column:
                  name: duration
                  value: "139"
              - column:
                  name: background_image
                  value: "/images/fight_club_bg.jpg"
              - column:
                  name: poster_image
                  value: "/images/fight_club_poster.jpg"
              - column:
                  name: arrival_of_cinema
                  value: "1999-10-15"

