server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5532}/cinema-db
    username: &username ${DB_CONNECTION_USERNAME:postgres}
    password: &password ${DB_CONNECTION_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: "SELECT 1"
    timeBetweenEvictionRunsMillis: 60000
    testOnBorrow: true
    validationInterval: 10000
    logValidationErrors: true
    hikari:
      leakDetectionThreshold: 30000
      validationTimeout: 300000
      removeAbandoned: true
      removeAbandonedTimeout: 60
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        temp:
          useJdbcMetadataDefaults: "false"
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          providerDisablesAutocommit: false
    showSql: true
    generateDdl: false
    openInView: false
    hibernate:
      ddlAuto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/cinema"
          jwk-set-uri: "http://localhost:8180/realms/cinema/protocol/openid-connect/certs"

jwt:
  auth:
    converter:
      resource-id: cinema-client

keycloak:
  realm: cinema
  host: http://127.0.0.1:8180
  clientId: admin-cli
  clientSecret: BWFNSrt1NZpGyEWOrWcDyJ4hW3kg1xFv
  grantType: client_credentials